# .github/workflows/debug-secrets.yml
name: Debug OAuth Settings

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if GDRIVE_CONFIG exists
      run: |
        if [ -z "${{ secrets.GDRIVE_CONFIG }}" ]; then
          echo "❌ GDRIVE_CONFIG secret is NOT set"
          echo "You need to create this secret with your OAuth configuration"
        else
          echo "✅ GDRIVE_CONFIG secret exists"
          echo "Checking format..."
          
          # 最初の50文字だけ表示（セキュリティのため）
          echo "First 50 characters:"
          echo "${{ secrets.GDRIVE_CONFIG }}" | head -c 50
          echo "..."
          
          # JSON形式チェック
          if echo "${{ secrets.GDRIVE_CONFIG }}" | jq . > /dev/null 2>&1; then
            echo "✅ Valid JSON format"
            echo "Keys in the JSON:"
            echo "${{ secrets.GDRIVE_CONFIG }}" | jq 'keys'
          else
            echo "❌ Invalid JSON format"
            echo "This is likely the cause of your error"
          fi
        fi
    
    - name: Check other possible secret names
      run: |
        echo "Checking for other possible secret names..."
        
        # 他の可能な名前もチェック
        if [ -n "${{ secrets.GOOGLE_DRIVE_CONFIG }}" ]; then
          echo "✅ Found: GOOGLE_DRIVE_CONFIG"
        fi
        
        if [ -n "${{ secrets.RCLONE_CONFIG }}" ]; then
          echo "✅ Found: RCLONE_CONFIG"
        fi
        
        if [ -n "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" ]; then
          echo "✅ Found: GDRIVE_SERVICE_ACCOUNT"
        fi
