# .github/workflows/yahooshot.yml
name: Yahoo Screenshot Auto

on:
  schedule:
    - cron: "0 0 * * *"     # 00:00 UTC = 09:00 JST
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Prepare output directory
        run: |
          mkdir -p /tmp/yahooshot

      - name: Configure rclone (safe write)
      env:
        RCLONE_CONF_CONTENT: ${{ secrets.RCLONE_CONF }}   # ← rclone.conf の全文をSecretsに保存してあること
      run: |
        curl -fsSL https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone
        # 改行を保ってファイルに書き出す
        printf "%s" "$RCLONE_CONF_CONTENT" > ~/.config/rclone/rclone.conf
        rclone --version


      - name: Run screenshot script (headless)
        env:
          YAHOOSHOT_OUTPUT_DIR: /tmp/yahooshot
        run: |
          python yahoo_shot.py

      - name: Upload to Google Drive (monthly folder)
        run: |
          YM=$(TZ=Asia/Tokyo date +%Y%m)         # 日本時間のYYYYMM
          rclone mkdir "gdrive:YahooShot/${YM}"  # 既存ならそのままスキップ
          rclone copy /tmp/yahooshot "gdrive:YahooShot/${YM}" -v

      - name: Cleanup
        if: always()
        run: rm -rf /tmp/yahooshot
