name: Yahoo Screenshot Auto

on:
  schedule:
    - cron: "0 0 * * *"     # 00:00 UTC = 日本時間 09:00
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ取得
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) 依存ライブラリ
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      # 4) Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # 5) 日本語フォント（豆腐対策）
      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-ipafont fonts-ipaexfont \
            fonts-noto-cjk fonts-noto-color-emoji
          fc-cache -fv

      # 6) 出力先
      - name: Prepare output directory
        run: |
          mkdir -p /tmp/yahooshot

      # 7) rclone設定（Secretsのrclone.conf全文を書き出し）
      - name: Configure rclone (safe write)
        env:
          RCLONE_CONF_CONTENT: ${{ secrets.RCLONE_CONF }}   # ← rclone.conf全文を保存してあること
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          printf "%s" "$RCLONE_CONF_CONTENT" > ~/.config/rclone/rclone.conf
          rclone --version

      # 8) スクショ実行（headless / iPhone16相当）
      - name: Run screenshot script (headless)
        env:
          YAHOOSHOT_OUTPUT_DIR: /tmp/yahooshot
          LANG: ja_JP.UTF-8
          LC_ALL: ja_JP.UTF-8
        run: |
          python yahoo_shot.py

      # 9) Google Drive の月別フォルダへアップロード
      - name: Upload to Google Drive (monthly folder)
        run: |
          YM=$(TZ=Asia/Tokyo date +%Y%m)
          rclone mkdir "gdrive:YahooShot/${YM}"
          rclone copy /tmp/yahooshot "gdrive:YahooShot/${YM}" -v

      # 10) 後片付け
      - name: Cleanup
        if: always()
        run: |
          rm -rf /tmp/yahooshot
